# Settings for orientation correction model
settings:
  correction_time_threshold: 0.3    # Threshold for time difference between the received imu message
                                  # and current time. (sec) 
  # X pointing forward, Y to the left, Z pointing up.
  rotation_imu2body: [0.2815 ,0 ,0 ,0.9595] # Orientation from odom to the body frame. [w, x, y, z]
  # rotation_odom2body: [0.4794, 0, 0.8776]
  # rotation_odom2body: [1, 0, 0, 0]
# Position noise parameters:
noises:
  orientation_std: 0.05 #5 #0.1
